name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        pg_version: [14, 15, 16, 17, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          build-args: |
            PG_VERSION=${{ matrix.pg_version }}
          tags: |
            ghcr.io/${{ github.repository }}:pg${{ matrix.pg_version }}
            ghcr.io/${{ github.repository }}:pg${{ matrix.pg_version }}-${{ github.sha }}
            ${{ matrix.pg_version == 18 && format('ghcr.io/{0}:latest', github.repository) || '' }}
